name: GitHub Streak

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create dist folder
        run: mkdir -p dist

      - name: Download Streak (Light)
        run: |
          curl -o dist/streak-light.svg "https://streak-stats.demolab.com?user=caitlon&theme=default&hide_border=false&border_radius=5"

      - name: Download Streak (Dark)
        run: |
          curl -o dist/streak-dark.svg "https://streak-stats.demolab.com?user=caitlon&theme=dracula&hide_border=false&border_radius=5"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          destination_dir: streak
          commit_message: "Update streak [skip ci]"
